server:
  port: 8084
spring:
  application:
    name: kong-eureka2
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8083/eureka
    register-with-eureka: false
#    fetch-registry: false