dubbo:
  application:
    name: user-service-privoder
  registry:
    address: 47.93.245.225:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20880
  monitor:
    protocol: registry


