server:
  port: 8085
spring:
  application:
    name: kong-service-customer
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8083/eureka,http://eureka2:8084/eureka
feign:
  hystrix:
    enabled: true