server:
  port: 8083
spring:
  application:
    name: kong-eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8084/eureka
    register-with-eureka: false
#    fetch-registry: false